### ISSUE TITLE
ResultSet closed exception

### ISSUE THREAD

**Issue by confuser** [j256/ormlite-jdbc#10]
I'm using this library in a large Minecraft server plugin as a MySQL ORM.

I've had multiple users reporting the same issue https://github.com/BanManagement/BanManager/issues/321

But I can't seem to narrow down what's causing it.

The area the exception is caught is at https://github.com/BanManagement/BanManager/blob/master/src/main/java/me/confuser/banmanager/runnables/BanSync.java#L42-L82

The query is built up within a BaseDaoImpl class and returns the iterator instance.

https://github.com/BanManagement/BanManager/blob/master/src/main/java/me/confuser/banmanager/storage/PlayerBanStorage.java#L135-L151

This iterator is then closed within BanSync after iteration is completed, no where else.

This is all ran on a worker thread, that is executed on a regular basis, but not necessarily from the same worker thread each time. Said runnable task has logic in place to prevent it from running again before the previous execution has completed.

As it only happens in production, reproducing in development environments is difficult/impossible.

Have I misunderstood something from the docs?

**Comment by j256** [comment]
Huh.  Can you post the actual exception the corresponds to that code?  Is it possible for the database instance or connection to be closed from under the worker thread?  What sort of connection source are you using?

**Comment by confuser** [comment]
Hi @j256 it's within the original issue I referenced, but I'll re-post it here for convenience.

```
[07:53:30] [Craft Scheduler Thread - 280/WARN]: Exception in thread "Craft Scheduler Thread - 280"
[07:53:30] [Craft Scheduler Thread - 280/WARN]: org.apache.commons.lang.UnhandledException: Plugin BanManager v5.6.0 generated an exception while executing task 34
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Errors getting more results of class me.confuser.banmanager.data.PlayerBanData
        at me.confuser.banmanager.internal.ormlite.stmt.SelectIterator.hasNext(SelectIterator.java:103)
        at me.confuser.banmanager.runnables.BanSync.newBans(BanSync.java:48)
        at me.confuser.banmanager.runnables.BanSync.run(BanSync.java:32)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
Caused by: java.sql.SQLException: Operation not allowed after ResultSet closed
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
        at com.mysql.jdbc.ResultSetImpl.checkClosed(ResultSetImpl.java:794)
        at com.mysql.jdbc.ResultSetImpl.next(ResultSetImpl.java:7145)
        at me.confuser.banmanager.internal.ormlite.jdbc.JdbcDatabaseResults.next(JdbcDatabaseResults.java:64)
        at me.confuser.banmanager.internal.ormlite.stmt.SelectIterator.hasNextThrow(SelectIterator.java:81)
        at me.confuser.banmanager.internal.ormlite.stmt.SelectIterator.hasNext(SelectIterator.java:98)
        ... 7 more
```

I'm using a JdbcPooledConnectionSource

https://github.com/BanManagement/BanManager/blob/master/src/main/java/me/confuser/banmanager/BanManager.java#L372-L399

The connections themselves are only ever closed when the plugin is disabled on shut down of the process. No where else in the code base are the close nor closeQuietly methods being explicitly called.

**Comment by j256** [comment]
Yeah I don't get it either.  This is trying to tell you that the `ResultSet` iterator has been closed on line 48 of BanSync.  But the only person closing it is outside in the finally block.

Any idea if the MySQL `ResultSetImpl.checkClosed(...)` closes check is actually checking whether the database connection is still valid?  Any chance you've been using this connection for a while and it needs to be re-opened or something?  Do you have connection testing enabled in the `JdbcPooledConnectionSource`?

**Comment by confuser** [comment]
https://github.com/BanManagement/BanManager/blob/master/src/main/java/me/confuser/banmanager/BanManager.java#L372-L399

`.setTestBeforeGet` is actually disabled, another developer said they found it caused a memory leak in a pull request, but I'm not familiar with the exact problem. Could the connection options be causing this? The MySQL URL does contain `?autoReconnect=true&failOverReadOnly=false&maxReconnects=10&useUnicode=true&characterEncoding=utf-8` which should be handling the auto reconnect, and that was the case before I switched from jdbc to ormlite.

**Comment by j256** [comment]
Hrm. So it is a bit strange to be making the updates inside of the resets look in a background thread.  However I don't think that the `ResetSet` connection is being used when you, for example, look at foreign objects and the like.  This typically calls back through the DAO which starts a new connection. 

One thing you might try is to record a list of bans within the iterator into another collection and then fire off the thread to process them _after_ the loop has finished and the ResultSet closed.  But that just may be reducing the loop and moving the problem.

**Comment by confuser** [comment]
So cache the results from the iterator into a collection, and then perform the checks on the data afterwards? I can see that potentially solving this issue, but buffering the results into memory defeats the purpose of using an iterator which would be far more memory efficient.

Could this issue be caused due to the foreign references within the data the iterator is pulling back? I'm not sure about how ormlite handles that, but if it's performing a separate query per object rather than using a join, could it be reusing statements causing them to close?

```
@DatabaseField(canBeNull = false, foreign = true, foreignAutoRefresh = true, uniqueIndex = true, persisterClass = ByteArray.class, columnDefinition = "BINARY(16) NOT NULL")
```

**Comment by j256** [comment]
Right now you are forking a task for every Ban you need to work on right.  Storing the `Ban` that you want to work on in a list _before_ building the async tasks shouldn't be that more overhead.

In terms of the foreign reference, that's what I was mentioning in my last comment.  I don't think so.  It uses the DAO and not the connection associated with the `ResetSet`.

**Comment by confuser** [comment]
Hi @j256 looking into this more, is it possible that this is caused by getting multiple iterators in different threads from the same DAO?

https://github.com/BanManagement/BanManager/blob/master/src/main/java/me/confuser/banmanager/runnables/BanSync.java#L46

https://github.com/BanManagement/BanManager/blob/master/src/main/java/me/confuser/banmanager/runnables/ExpiresSync.java#L34-L35

Both of these may overlap at some point

**Comment by confuser** [comment]
This is still an issue @j256 I've changed to HikariCP for connection handling as there is an issue with the inbuilt pooling system in which it opens more connections than the maximum allowed limit.

People are still raising issues with errors stating `ResultSet closed` https://github.com/BanManagement/BanManager/issues/493

**Comment by j256** [comment]
Did you ever figure this out @confuser ?

**Comment by confuser** [comment]
Unfortunately not @j256 still at a loss as to the cause

**Comment by confuser** [comment]
Someone did report a similar error, but the stack trace shows connection closed rather than ResultSet closed.

```
[11:18:16] [Craft Scheduler Thread - 6/WARN]: Exception in thread "Craft Scheduler Thread - 6"
[11:18:16] [Craft Scheduler Thread - 6/WARN]: org.apache.commons.lang.UnhandledException: Plugin BanManager v5.10.0-SNAPSHOT generated an exception while executing task 3162
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Errors getting more results of class me.confuser.banmanager.data.PlayerWarnData
        at me.confuser.banmanager.internal.ormlite.stmt.SelectIterator.hasNext(SelectIterator.java:103)
        at me.confuser.banmanager.listeners.JoinListener$1.run(JoinListener.java:236)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
Caused by: java.sql.SQLException: Connection is closed
        at me.confuser.banmanager.internal.hikari.pool.ProxyConnection$ClosedConnection$1.invoke(ProxyConnection.java:468)
        at com.sun.proxy.$Proxy32.clearWarnings(Unknown Source)
        at me.confuser.banmanager.internal.hikari.pool.ProxyConnection.close(ProxyConnection.java:241)
        at me.confuser.banmanager.internal.ormlite.jdbc.JdbcDatabaseConnection.close(JdbcDatabaseConnection.java:139)
        at me.confuser.banmanager.internal.ormlite.jdbc.DataSourceConnectionSource.releaseConnection(DataSourceConnectionSource.java:130)
        at me.confuser.banmanager.internal.ormlite.stmt.SelectIterator.close(SelectIterator.java:247)
        at me.confuser.banmanager.internal.ormlite.stmt.SelectIterator.hasNextThrow(SelectIterator.java:84)
        at me.confuser.banmanager.internal.ormlite.stmt.SelectIterator.hasNext(SelectIterator.java:98)
        ... 6 more
```

Obviously connections closing would also close any ResultSets associated with the connection resource. Seems like a more likely cause?

**Comment by j256** [comment]
I guess so.  Are you holding iterators open for long periods of time?  That certainly is not recommended.  Not sure what we can do to help with this.  Any ideas?

**Comment by confuser** [comment]
Looks like this was caused by a mix between concurrency and race conditions. Forcing the tasks into the same thread seems to have solved this issue.
