### ISSUE TITLE
Succeed use for SQLite in Windows, but failed in Mac.

### ISSUE THREAD

**Issue by amrishodiq** [j256/ormlite-jdbc#30]
I've implement an application, it works when I code in Windows. But the same code gave Exception in Mac. I use SQLite database and have put sqlite-jdbc-3.21.0.1.jar as library.  

I know the driver went ok since I have check it like below:
```
public static void pureSqlite() throws Exception {
        String url = "jdbc:sqlite:hadits-bukhari.sqlite";
        Connection connection = DriverManager.getConnection(url);
        System.out.println("Connection established.");
        
        String sql = "SELECT * FROM hadits";
        Statement statement = connection.createStatement();
        ResultSet resultSet = statement.executeQuery(sql);
        
        int i = 0;
        while (resultSet.next()) {
            if (i == 5) break;
            
            System.out.println(resultSet.getInt("nomer")+". "+resultSet.getString("deskripsi"));
            
            i++;
        }
    }
```
It works perfectly.

Then, I've implement it with ORMLite's way. Create Hadits class with required annotation. Then I have below function:

```
public static void withOrmLite() throws Exception {
        Class.forName("org.sqlite.JDBC"); // even put this test
        System.out.println("Frankly, class org.sqlite.JDBC is exists."); 

        Ilmu ilmu = new IlmuImpl();
        List<Hadits> list = ilmu.findHadits("bukhari", "");
        int i = 0;
        for (Hadits item: list) {
            if (i == 10) break;
            System.out.println(item.number+". "+item.desc);
            i++;
        }
    }
```
From IlmuImpl:
```
@Override
    public List<Hadits> findHadits(String book, String keyword) throws Exception {
        String dbHost = "jdbc:sqlite:hadits-"+book+".sqlite";
        ConnectionSource connection = new JdbcConnectionSource(dbHost);
        Dao<Hadits, Long> haditsDao = DaoManager.createDao(connection, Hadits.class);
        
        List<Hadits> list;
        
        if (keyword == null || keyword.trim().length() == 0) {
            list = haditsDao.queryForEq("buku", book);
        } else {
            QueryBuilder<Hadits, Long> queryBuilder = haditsDao.queryBuilder();
            queryBuilder.where().like("deskripsi", "%"+keyword+"%");
            PreparedQuery<Hadits> preparedQuery = queryBuilder.prepare();
            list = haditsDao.query(preparedQuery);
        }
        
        
        connection.close();
        return list;
    }
```

This code do fine in Windows, but failed in Mac, says:

```
Exception in thread "main" java.sql.SQLException: Driver class was not found for SQLite database.  Missing jar with class org.sqlite.JDBC.
	at com.j256.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:27)
	at com.j256.ormlite.db.BaseDatabaseType.loadDriver(BaseDatabaseType.java:47)
	at com.j256.ormlite.jdbc.JdbcConnectionSource.initialize(JdbcConnectionSource.java:137)
	at com.j256.ormlite.jdbc.JdbcConnectionSource.<init>(JdbcConnectionSource.java:117)
	at com.j256.ormlite.jdbc.JdbcConnectionSource.<init>(JdbcConnectionSource.java:59)
	at ilmu.implementation.IlmuImpl.findHadits(IlmuImpl.java:17) <-- this is my class
...
Caused by: java.lang.ClassNotFoundException: org.sqlite.JDBC
...
```

What could be wrong?

**Comment by AshishGaur28** [comment]
I'm also facing the same issue. Were you able to find any solution?

**Comment by j256** [comment]
Typically this means that you are not loading one of the sqlite driver jars.  For example, you maybe should add the following to your `pom.xml` file if you are using maven:

	<dependency>
		<groupId>org.xerial</groupId>
		<artifactId>sqlite-jdbc</artifactId>
		<version>3.32.3.2</version>
	</dependency>

**Comment by AshishGaur28** [comment]
Thanks for the quick reply. I was able to make it work after including the above mentioned dependency
