### ISSUE TITLE
UnsatisfiedLinkError: couldn't find "libsqlitejdbc.so"

### ISSUE THREAD

**Issue by lparolari** [j256/ormlite-jdbc#32]
Hello,

I was using this library for sqlite operations: I made a library which manage sqlite databse, and I imported the library to an android app, but when I run the android app something strange happens.

This is the error:

```
05-16 23:30:55.997 8223-8223/it.lparolari.testlib E/AndroidRuntime: FATAL EXCEPTION: main
    Process: it.lparolari.testlib, PID: 8223
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/it.lparolari.testlib-b8f6toZXRayhuUF3izubeg==/base.apk", zip file "/data/app/it.lparolari.testlib-b8f6toZXRayhuUF3izubeg==/split_lib_dependencies_apk.apk", zip file "/data/app/it.lparolari.testlib-b8f6toZXRayhuUF3izubeg==/split_lib_resources_apk.apk", zip file "/data/app/it.lparolari.testlib-b8f6toZXRayhuUF3izubeg==/split_lib_slice_0_apk.apk", zip file "/data/app/it.lparolari.testlib-b8f6toZXRayhuUF3izubeg==/split_lib_slice_1_apk.apk", zip file "/data/app/it.lparolari.testlib-b8f6toZXRayhuUF3izubeg==/split_lib_slice_2_apk.apk", zip file "/data/app/it.lparolari.testlib-b8f6toZXRayhuUF3izubeg==/split_lib_slice_3_apk.apk", zip file "/data/app/it.lparolari.testlib-b8f6toZXRayhuUF3izubeg==/split_lib_slice_4_apk.apk", zip file "/data/app/it.lparolari.testlib-b8f6toZXRayhuUF3izubeg==/split_lib_slice_5_apk.apk", zip file "/data/app/it.lparolari.testlib-b8f6toZXRayhuUF3izubeg==/split_lib_slice_6_apk.apk", zip file "/data/app/it.lparolari.testlib-b8f6toZXRayhuUF3izubeg==/split_lib_slice_7_apk.apk", zip file "/data/app/it.lparolari.testlib-b8f6toZXRayhuUF3izubeg==/split_lib_slice_8_apk.apk", zip file "/data/app/it.lparolari.testlib-b8f6toZXRayhuUF3izubeg==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/it.lparolari.testlib-b8f6toZXRayhuUF3izubeg==/lib/x86, /system/lib]]] couldn't find "libsqlitejdbc.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1657)
        at org.sqlite.core.NativeDB.<clinit>(NativeDB.java:38)
        at org.sqlite.core.NativeDB.load(NativeDB.java:53)
        at org.sqlite.core.CoreConnection.open(CoreConnection.java:211)
        at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76)
        at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:26)
        at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:24)
        at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
        at org.sqlite.JDBC.createConnection(JDBC.java:114)
        at org.sqlite.JDBC.connect(JDBC.java:88)
        at java.sql.DriverManager.getConnection(DriverManager.java:569)
        at java.sql.DriverManager.getConnection(DriverManager.java:191)
        at com.j256.ormlite.jdbc.JdbcConnectionSource.makeConnection(JdbcConnectionSource.java:266)
        at com.j256.ormlite.jdbc.JdbcConnectionSource.getReadWriteConnection(JdbcConnectionSource.java:187)
        at com.j256.ormlite.misc.TransactionManager.callInTransaction(TransactionManager.java:174)
        at com.j256.ormlite.misc.TransactionManager.callInTransaction(TransactionManager.java:158)
        at it.bcv.invade.appdb.Migrator.execute(Migrator.java:56)
        [...]
        at it.lparolari.test.testlib.MainActivity.onCreate(MainActivity.java:43)
        [...]
```

What is this error? How can i fix this? I've searched around the web and I didn't find anything that match my problem, what can i do?

Thanks in advance.

**Comment by j256** [comment]
Sorry I don't have any information.  If this is under android then I don't have a lot of experience compared to the Android port of ORMLite.

**Comment by lparolari** [comment]
My user library was trying to create a jdbc connection source from a string, instanced on a sqlite database over android.
I've rearranged my lib's interface: now the lib takes a ConnectionSource, and from android I create and give an AndroidConnectionSource to it. This solved the problem.

**Comment by chyngyzturap** [comment]
@lparolari 
Hi there! Please, can you share me code of your realization? Can't find solutions, but it seems that I found in your answers. Cause goals of library the same.
