### ISSUE TITLE
`generatedId` field not supported since Xerial SQLite driver 3.43.0.0

### ISSUE THREAD

**Issue by Phoenix616** [j256/ormlite-jdbc#83]
Specifying a field of a Class as `generatedId` and calling `Dao#create` throws an exception of that not being supported. (Which is true in SQLite) This worked previously with version 3.42.0.0 of the driver. I'm not sure if they actually changed something as [this issue alludes to](https://github.com/xerial/sqlite-jdbc/issues/963) or if some internal detection for supported features broke.

Used ORMLite version: `6.1` (latest release, as far as I can tell the last snapshot commit doesn't change anything)

The error stacktrace:

```
[13:24:50] [Server thread/ERROR]: [ChestShop] Unable to get code of item ItemStack{FILLED_MAP x 1, MAP_META:{meta-type=MAP, map-id=45}}
java.sql.SQLException: Unable to run insert stmt on object com.Acrobot.ChestShop.Database.Item@511a7f3e: INSERT INTO `items` (`id` ,`code` ) VALUES (?,?)
	at com.Acrobot.ChestShop.Libs.ORMlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:139) ~[?:?]
	at com.Acrobot.ChestShop.Libs.ORMlite.stmt.StatementExecutor.create(StatementExecutor.java:464) ~[?:?]
	at com.Acrobot.ChestShop.Libs.ORMlite.dao.BaseDaoImpl.create(BaseDaoImpl.java:337) ~[?:?]
	at com.Acrobot.ChestShop.Metadata.ItemDatabase.getItemCode(ItemDatabase.java:155) ~[?:?]
	at com.Acrobot.Breeze.Utils.MaterialUtil$Metadata.getItemCode(MaterialUtil.java:524) ~[?:?]
	at com.Acrobot.Breeze.Utils.MaterialUtil.getName(MaterialUtil.java:280) ~[?:?]
	at com.Acrobot.ChestShop.Listeners.Item.ItemStringListener.calculateItemString(ItemStringListener.java:14) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at com.Acrobot.ChestShop.ChestShop.callEvent(ChestShop.java:614) ~[?:?]
	at com.Acrobot.ChestShop.Utils.ItemUtil.getName(ItemUtil.java:56) ~[?:?]
	at com.Acrobot.ChestShop.Utils.ItemUtil.getName(ItemUtil.java:44) ~[?:?]
	at com.Acrobot.ChestShop.Commands.ItemInfo.sendItemName(ItemInfo.java:69) ~[?:?]
	at com.Acrobot.ChestShop.Commands.ItemInfo.onCommand(ItemInfo.java:51) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchCommand(CraftServer.java:879) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3890-Spigot-a0f3d48-df3738a]
	at org.bukkit.craftbukkit.v1_20_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3890-Spigot-a0f3d48-df3738a]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:320) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3890-Spigot-a0f3d48-df3738a]
	at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:304) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3890-Spigot-a0f3d48-df3738a]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1827) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3890-Spigot-a0f3d48-df3738a]
	at net.minecraft.server.network.PlayerConnection.lambda$15(PlayerConnection.java:1789) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3890-Spigot-a0f3d48-df3738a]
	at net.minecraft.util.thread.IAsyncTaskHandler.b(SourceFile:67) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3890-Spigot-a0f3d48-df3738a]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run$$$capture(CompletableFuture.java:1768) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java) ~[?:?]
	at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3890-Spigot-a0f3d48-df3738a]
	at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:156) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3890-Spigot-a0f3d48-df3738a]
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3890-Spigot-a0f3d48-df3738a]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1133) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3890-Spigot-a0f3d48-df3738a]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3890-Spigot-a0f3d48-df3738a]
	at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:130) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3890-Spigot-a0f3d48-df3738a]
	at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1112) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3890-Spigot-a0f3d48-df3738a]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1105) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3890-Spigot-a0f3d48-df3738a]
	at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:139) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3890-Spigot-a0f3d48-df3738a]
	at net.minecraft.server.MinecraftServer.u_(MinecraftServer.java:1089) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3890-Spigot-a0f3d48-df3738a]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1000) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3890-Spigot-a0f3d48-df3738a]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:298) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3890-Spigot-a0f3d48-df3738a]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.sql.SQLFeatureNotSupportedException: not implemented by SQLite JDBC driver
	at org.sqlite.jdbc3.JDBC3PreparedStatement.unsupported(JDBC3PreparedStatement.java:448) ~[sqlite-jdbc-3.43.0.0.jar:?]
	at org.sqlite.jdbc3.JDBC3Statement.getGeneratedKeys(JDBC3Statement.java:357) ~[sqlite-jdbc-3.43.0.0.jar:?]
	at com.Acrobot.ChestShop.Libs.ORMlite.jdbc.JdbcDatabaseConnection.insert(JdbcDatabaseConnection.java:188) ~[?:?]
	at com.Acrobot.ChestShop.Libs.ORMlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:91) ~[?:?]
	... 44 more
```

This is from the Minecraft-plugin ChestShop. The create-call is [here](https://github.com/ChestShop-authors/ChestShop-3/blob/master/src/main/java/com/Acrobot/ChestShop/Metadata/ItemDatabase.java#L155) and the used [Item.class](https://github.com/ChestShop-authors/ChestShop-3/blob/master/src/main/java/com/Acrobot/ChestShop/Database/Item.java) for [the Dao](https://github.com/ChestShop-authors/ChestShop-3/blob/master/src/main/java/com/Acrobot/ChestShop/Metadata/ItemDatabase.java#L43).

**Comment by Phoenix616** [comment]
Just noticed #82 and https://github.com/j256/ormlite-core/issues/288, sorry about the duplicate issue. A fix would be very appreciated though!
